export const methodsArray = [
  { id: 1, name: "University of Islamic Sciences, Karachi" },
  { id: 2, name: "Islamic Society of North America (ISNA)" },
  { id: 3, name: "Muslim World League" },
  { id: 4, name: "Umm Al-Qura University, Makkah" },
  { id: 5, name: "Egyptian General Authority of Survey" },
  { id: 6, name: "" },
  { id: 7, name: "Institute of Geophysics, University of Tehran" },
  { id: 8, name: "Gulf Region" },
  { id: 9, name: "Kuwait" },
  { id: 10, name: "Qatar" },
  { id: 11, name: "Majlis Ugama Islam Singapura, Singapore" },
  { id: 12, name: "Union Organization Islamic de France" },
  { id: 13, name: "Diyanet İşleri Başkanlığı, Turkey (experimental)" },
  { id: 14, name: "Spiritual Administration of Muslims of Russia" },
  { id: 15, name: "Moonsighting Committee Worldwide (Moonsighting.com)" },
  { id: 16, name: "Dubai (experimental)" },
  { id: 17, name: "Jabatan Kemajuan Islam Malaysia (JAKIM)" },
  { id: 18, name: "Tunisia" },
  { id: 19, name: "Algeria" },
  { id: 20, name: "Kementerian Agama Republik Indonesia" },
  { id: 21, name: "Morocco" },
  { id: 22, name: "Comunidade Islamica de Lisboa" },
  { id: 23, name: "Ministry of Awqaf, Islamic Affairs and Holy Places, Jordan" }
];

export const arMethodsArray = [
  { id: 1, name: "جامعة العلوم الإسلامية، كراتشي" },
  { id: 2, name: "الجمعية الإسلامية لأمريكا الشمالية (ISNA)" },
  { id: 3, name: "رابطة العالم الإسلامي" },
  { id: 4, name: "جامعة أم القرى، مكة" },
  { id: 5, name: "الهيئة العامة للمساحة، مصر" },
  { id: 6, name: "" },
  { id: 7, name: "معهد الجيوفيزياء، جامعة طهران" },
  { id: 8, name: "المنطقة الخليجية" },
  { id: 9, name: "الكويت" },
  { id: 10, name: "قطر" },
  { id: 11, name: "مجلس الأئمة الإسلامي في سنغافورة" },
  { id: 12, name: "الاتحاد الإسلامي في فرنسا" },
  { id: 13, name: "رئاسة الشؤون الدينية، تركيا (تجريبي)" },
  { id: 14, name: "الإدارة الروحية لمسلمي روسيا" },
  { id: 15, name: "لجنة رؤية الهلال العالمية (Moonsighting.com)" },
  { id: 16, name: "دبي (تجريبي)" },
  { id: 17, name: "إدارة الشؤون الإسلامية في ماليزيا (JAKIM)" },
  { id: 18, name: "تونس" },
  { id: 19, name: "الجزائر" },
  { id: 20, name: "وزارة الشؤون الدينية، إندونيسيا" },
  { id: 21, name: "المغرب" },
  { id: 22, name: "الجالية الإسلامية في لشبونة" },
  { id: 23, name: "وزارة الأوقاف والشؤون الإسلامية والأماكن المقدسة، الأردن" },

];
